
name: jira-description-action
on:
  pull_request:
    types: [opened, reopened]
    branches: 
    - main
jobs:
  add-jira-description:
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: https://fractalenterprises.atlassian.net
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}

      - name: MainBranch Checkout
        uses: actions/checkout@v2
  
      - name: Finding JIRA tickets in title
        uses: atlassian/gajira-find-issue-key@master
        with:
          string: ${{ github.event.pull_request.title  }}        
          
      - name: Finding JIRA tickets in branch
        uses: atlassian/gajira-find-issue-key@master
        with:
          from: branch

      - name: Finding JIRA tickets in commit
        uses: atlassian/gajira-find-issue-key@master
        with:
          from: commits
          
      - name: JIRA issues
        run: |
          if [ ! -f "~/jira/config.yml" ] 
          then
            exit 1
          fi 
#          string: ${{ join( github.event.pull_request.title , github.event.pull_request.body ) }}
#          from: branch,commit
#      - name: jira-description
#        uses: cakeinpanic/jira-description-action@v0.3.0
#        id: jira-description-action
#        with:
#          github-token: ${{ secrets.NSLHB_TEST_TOKEN }}
#          jira-token: ${{ secrets.JIRA_TOKEN }}
#          jira-base-url: https://fractalenterprises.atlassian.net
#          use: both
#          custom-issue-number-regexp: '^[A-Z]+-\d+' 
#          fail-when-jira-issue-not-found: true
##      - uses: peter-evans/close-pull@v1.1.3
#        name: close-pull
#        id: close-pull
#        if: ${{ failure() && always() }}
#        with:
#          pull-request-number: ${{ github.event.number }}
#          comment: |
#            Closing pull request because it doesn't reference any Jira issues.
#            Try branch name or PR title with the below format:
#            Ex: SRE-XX bug fix
#          delete-branch: false
