name: main-branch-push
on:
 push: 
   branches:
     - main
jobs:
  qa-pr-creation-or-updation:
    runs-on: ubuntu-latest
    steps: 
    - name: pull-request-action
      id: pull_request
      uses: vsoch/pull-request-action@master
      env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PULL_REQUEST_BRANCH: "prod"
            PULL_REQUEST_FROM_BRANCH: "main"
            PULL_REQUEST_TITLE: "Auto PR"
            PULL_REQUEST_BODY: "```release-note \n ```"
            PASS_IF_EXISTS: true
            PULL_REQUEST_UPDATE: true
  auto-update:
    runs-on: ubuntu-latest
    steps:
    - name: autoupdate
      uses: docker://chinthakagodawita/autoupdate-action:v1
      env:
       GITHUB_TOKEN: '${{ secrets.NSLHB_TEST_TOKEN  }}'
       MERGE_MSG: "Branch was auto-updated with main branch"    
#    - name: update-pull-request
#      uses: kt3k/update-pr-description@v1.0.1
#      with:
#        pr_body: |
#                test1
#        source_branch: main        
#        destination_branch: prod
#        github_token: ${{ secrets.GITHUB_TOKEN }}

#    - name: Test outputs
#      env:
#          pull_request_number_output: ${{ steps.pull_request.outputs.pull_request_number }}
#          pull_request_url_output: ${{ steps.pull_request.outputs.pull_request_url }}
#      run: |
#          echo "Pull request number from output: ${pull_request_number_output}"
#          echo "Pull request url from output: ${pull_request_url_output}"
#          echo "Pull request number from environment: ${PULL_REQUEST_NUMBER}"
#          echo "Pull request url from environment: ${PULL_REQUEST_URL}"
#          echo "Another way to specify from output ${{ steps.pull_request.outputs.pull_request_number }}"
#       CURRENT_PR_BODY=`curl https://api.github.com/repos/nslhub/project/pulls/${{ steps.pull-request-action.outputs.pull_request_number }} | grep body | cut -d'"' -f4`        
#        echo "${CURRENT_PR_BODY}\n\n${NEW_PR_BODY}"
#         ${{ steps.pull_request.outputs.pull_request_url }}             
#    - name: updating PR Body
#      if: ${{ success() }}
#      uses: tzkhan/pr-update-action@v2
#      with:
#        repo-token: '${{ secrets.NSLHB_TEST_TOKEN }}'
#        base-branch-regex: 'main'
#        head-branch-regex: 'prod'
#        body-template: |
#          "&"
#          "${{ github.event.pull_request.number }}"  
#          "${{ github.event.pull_request.body }}"
#        body-update-action: 'suffix'

   
