name: qa-pr
on:
 pull_request: 
   types:
     - closed
   branches:
     - main
jobs:
  qa-pr-creattion-or-updation:
    runs-on: ubuntu-latest
    steps: 
    - name: pull-request-action
      uses: vsoch/pull-request-action@master
      env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PULL_REQUEST_BRANCH: "prod"
            PULL_REQUEST_FROM_BRANCH: "main"
            PULL_REQUEST_TITLE: "Auto PR"
            PASS_IF_EXISTS: true

    - name: PR Body 
      run: |
        NEW_PR_BODY=`curl https://api.github.com/repos/nslhb/javamaventestrepo/pulls/${{ github.event.pull_request.number }} | grep body | cut -d'"' -f4`
        
#       CURRENT_PR_BODY=`curl https://api.github.com/repos/nslhub/project/pulls/${{ steps.pull-request-action.outputs.pull_request_number }} | grep body | cut -d'"' -f4`        
#        echo "${CURRENT_PR_BODY}\n\n${NEW_PR_BODY}"
#         ${{ steps.pull_request.outputs.pull_request_url }}             
#    - name: updating PR Body
#      if: ${{ success() }}
#      uses: tzkhan/pr-update-action@v2
#      with:
#        repo-token: '${{ secrets.NSLHB_TEST_TOKEN }}'
#        base-branch-regex: 'main'
#        head-branch-regex: 'prod'
#        body-template: |
#          "&"
#          "${{ github.event.pull_request.number }}"  
#          "${{ github.event.pull_request.body }}"
#        body-update-action: 'suffix'

   
