name: sonar-scan
on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.NSLHB_TEST_TOKEN }}
        SONAR_TOKEN: ${{ secrets.NSLHB_SONAR_TOKEN }}
      with:
        args: >
         -Dsonar.branch.name=main
         -Dsonar.host.url=https://sonarcloud.io/organizations/nslhb
         -Dsonar.organization=nslhb
         -Dsonar.projectKey=JavaMavenTestRepo 
         -Dsonar.projectName=JavaMavenTestRepo 
         -Dsonar.language=java 
         -Dsonar.sources=src/main/java 
         -Dsonar.tests=src/test/java 
         -Dsonar.dynamicAnalysis=reuseReports 
         -Dsonar.junit.reportsPath=/target/test-reports 
         -Dsonar.java.coveragePlugin=jacoco 
         -Dsonar.jacoco.reportPath=/target/site/jacoco/index.html
