name: post-pr-merge-workflow
on: 
  push:
    branches:
      - main    
jobs:
  post-pr:
    runs-on: ubuntu-latest 
    steps:
    - name: update-pull-request
      uses: kt3k/update-pr-description@v1.0.1
      with:
        pr_body: |
                test
        destination_branch: prod
        github_token: ${{ secrets.GITHUB_TOKEN }}
