name: unit-test

on:
  pull_request:
    branches:
    - 'main'
    paths-ignore:
    - 'README.md'
    - 'OWNERS'
    - 'OWNERS_ALIASES'  

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Step 1 - MainBranch Checkout
      uses: actions/checkout@v2
    - name: Step 2 - JDK SETUP
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'        
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4
      with:
          maven-version: 3.8.1
    - name: Run Test 
      id: tests
      run: |
        echo "::set-output name=test_result::false"  
        mvn test
        echo "::set-output name=test_result::true"  
    - name: adding paased label
      uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: |
          unit-tests-approved       
        github_token: '${{ secrets.NSLHB_TEST_TOKEN }}'         
    - name: removing failed label
      if: ${{ contains( github.event.pull_request.labels.*.name, 'do-not-merge/unit-tests-restiction') }}
      uses: actions-ecosystem/action-remove-labels@v1
      with:
        labels: |
          do-not-merge/unit-tests-restiction
        github_token: '${{ secrets.NSLHB_TEST_TOKEN }}'
    - name: adding passed comments
      uses: mshick/add-pr-comment@v1
      with:
        message: |
          Unit Tests Passed 
        repo-token: ${{ secrets.NSLHB_TEST_TOKEN }}
        repo-token-user-login: 'github-actions[bot]' 
        allow-repeats: true    
    - name: adding failed comments
      if: ${{ steps.tests.outputs.test_result  == 'failure' && always() }}
      uses: mshick/add-pr-comment@v1
      with:
        message: |
          Unit Tests Failed 
        repo-token: ${{ secrets.NSLHB_TEST_TOKEN }}
        repo-token-user-login: 'github-actions[bot]' 
        allow-repeats: true
    - name: adding failed label
      if: ${{ steps.tests.outputs.test_result  == 'failure' && always() }}
      uses: actions-ecosystem/action-remove-labels@v1
      with:
        labels: |
          do-not-merge/unit-tests-restiction
        github_token: '${{ secrets.NSLHB_TEST_TOKEN }}' 
    - name: removing passed label
      if: ${{ steps.tests.outputs.test_result  == 'failure' && always()  && contains( github.event.pull_request.labels.*.name, 'unit-tests-restiction')}}
      uses: actions-ecosystem/action-remove-labels@v1
      with:
        labels: |
          unit-tests-approved
        github_token: '${{ secrets.NSLHB_TEST_TOKEN }}'
        
